name: Set GitHub Secrets

on:
  push:
    branches: [main]
    paths: ['github-secrets-mapping.yml']
  workflow_dispatch: {}

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set secrets based on definition
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_SECRET_ASCII_ARMORED: ${{ secrets.GPG_SECRET_ASCII_ARMORED }}
          GRADLE_API_KEY: ${{ secrets.GRADLE_API_KEY }}
          GRADLE_API_SECRET: ${{ secrets.GRADLE_API_SECRET }}
          OSSRH_KEY: ${{ secrets.OSSRH_KEY }}
          OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
        run: docker run --rm \
          -e DIGITALOCEAN_ACCESS_TOKEN \
          -e DOCKERHUB_USER \
          -e DOCKERHUB_TOKEN \
          -e GH_CONTAINER_REGISTRY_TOKEN \
          -e GH_PAT \
          -e GPG_PASSWORD \
          -e GPG_SECRET_ASCII_ARMORED \
          -e GRADLE_API_KEY \
          -e GRADLE_API_SECRET \
          -e OSSRH_KEY \
          -e OSSRH_USER_TOKEN \
          --mount type=bind,source="$(pwd)"/github-secrets-mapping.yml,target=/github-secrets-mapping.yml hildan/bob set-github-secrets-batch -t ${{ secrets.GH_PAT }} -f /github-secrets-mapping.yml --dry-run
