name: Set GitHub Secrets

on:
  push:
    branches: [main]
    paths: ['github-secrets-mapping.yml']
  workflow_dispatch: {}

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set batch secrets
        run: docker run hildan/bob set-github-secrets-batch -t ${{ secrets.GH_PAT }} -f github-secrets-mapping.yml --dry-run
